[package]
name = "common"
version = "0.1.0"
edition = "2018"


[dev-dependencies]
criterion = "0.5.1"

#[[bench]]
#name = "my_benchmark"
#harness = false

[dependencies]
num-traits = "0.2.18"
rand = "0.8.5"
transpose = "0.2.3"

